output_dir: ${SCRATCH}/heptrkx/results/resmpnn_005

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_high_000
    n_train: 57344
    n_valid: 4096
    real_weight: 5 #6.25  # 0.5 / 0.08
    batch_size: 4
    n_workers: 4

model:
    name: resmpnn
    input_dim: 3
    hidden_node_dim: 64
    hidden_edge_dim: 64
    n_graph_iters: 8
    layer_norm: true
    loss_func: binary_cross_entropy_with_logits

optimizer:
    name: Adam
    learning_rate: 0.001
    #lr_scaling: sqrt
    #lr_warmup_epochs: 5
    lr_decay_schedule:
        - {start_epoch: 64, end_epoch: 128, factor: 0.1}

training:
    n_total_epochs: 128
